export const jobOptions = [
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile App Developer",
    "Data Scientist",
    "UI/UX Designer",
    "Software Engineer",
    "Machine Learning Engineer",
    "Cloud Solutions Architect",
    "DevOps Engineer",
    "Network Administrator",
    "Database Administrator",
    "Game Developer",
    "Cybersecurity Analyst",
    "Embedded Systems Engineer",
    "Artificial Intelligence Specialist",
    "Robotics Engineer",
    "Blockchain Developer",
    "Quality Assurance Engineer",
    "Systems Analyst",
    "Network Security Specialist",
    "Project Manager",
    "Marketing Specialist",
    "Human Resources Manager",
    "Business Analyst",
    "Financial Analyst",
    "Sales Representative",
    "Content Writer",
    "Graphic Designer",
    "Customer Support Specialist",
    "Operations Manager",
    "Supply Chain Manager",
    "Public Relations Specialist",
    "Technical Writer",
    "Event Planner",
    "Accountant",
    "Data Analyst",
    "Market Research Analyst",
    "Logistics Coordinator",
    "Executive Assistant",
    "Translator",
    "Other"
  ];
